import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          {/* Top Nav */}
          <header className="h-16 bg-gray-900 text-white flex items-center px-6">
            <h1 className="text-xl font-bold">Nudge Spend Save</h1>
          </header>

          <div className="flex flex-1">
            {/* Sidebar */}
            <aside className="w-64 bg-gray-100 p-4">
              <nav className="flex flex-col gap-4">
                <a href="/" className="hover:underline">Home</a>
                <a href="/dashboard" className="hover:underline">Dashboard</a>
                <a href="#" className="hover:underline">Budgets</a>
                <a href="#" className="hover:underline">Settings</a>
              </nav>
            </aside>

            {/* Main Content */}
            <main className="flex-1">{children}</main>
          </div>

          <footer className="h-12 bg-gray-200 flex items-center justify-center text-sm">
            &copy; 2025 Nudge Spend Save
          </footer>
        </div>
      </body>
    </html>
  );
}
